name: Deploy to Azure App Service

on: 
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: setup the Node.js version
        uses: actions/setup-node@v4
        with: 
          node-version: '18.x'

      - name: Change directory to API
        run: cd API

      - name: install dependencies
        run: npm install --legacy-peer-deps
        working-directory: ./API

      - name: List deployed files
        run: ls -R ./API


      - name: Deploy to Azure app Services
        uses: azure/webapps-deploy@v2
        with: 
          app-name: MAPD713APIProject
          publish-profile: ${{ secrets.MAPD713_SECRET }}
          package: ./API